spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-pacientes-route
          uri: lb://ms-pacientes
          predicates:
            - Path=/pacientes/**
        - id: ms-citas-route
          uri: lb://ms-citas
          predicates:
            - Path=/citas/**
        - id: ms-facturacion-route
          uri: lb://ms-facturacion
          predicates:
            - Path=/facturas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
